#RequireAdmin
ShellExecuteWait(@ScriptDir & '\cloudbaseinit.msi')
AutoItSetOption('MouseCoordMode',0)
Opt("WinTitleMatchMode", 2)
Sleep(2000)
WinWait('Cloudbase-Init')
WinActivate('Cloudbase-Init')
MouseClick('primary', 360, 362, 1, 0)
WinWait('Cloudbase-Init')
WinActivate('Cloudbase-Init')
;Click Accept Eula & Next
ControlCommand('Cloudbase-Init', 'I &accept the terms in the License Agreement', 'Button1','Check')
MouseClick('primary', 360, 362, 1, 0)
;Custom Setup Page, Use Default Settings
WinWait('Cloudbase-Init')
WinActivate('Cloudbase-Init')
MouseClick('primary', 370, 362, 1, 0)
;Configuration Page, insert username, select metadata password,select serial port and check Run as Local System
WinWait('Cloudbase-Init', 'Use metadata &password')
WinActivate('Cloudbase-Init', 'Use metadata &password')
Sleep(300)
Send('<Username>')
Send('{TAB}{TAB}{TAB}{HOME}')
Sleep(500)
ControlCommand('Cloudbase-Init', 'Use metadata &password', 'Button1','Check')
ControlCommand('Cloudbase-Init', 'Run Cloudbase-Init service as &LocalSystem', 'Button2','Check')
MouseClick('primary', 360, 362, 1, 0)
;Install Confirmation page
WinWait('Cloudbase-Init', 'Click Install to begin the installation')
WinActivate('Cloudbase-Init', 'Click Install to begin the installation')
MouseClick('primary', 339, 361, 1, 0)
;Complete Page and Ask for Sysprep (Just Click finish)
WinWait('Cloudbase-Init', 'Click the Finish button to exit the Setup Wizard')
WinActivate('Cloudbase-Init', 'Click the Finish button to exit the Setup Wizard')
MouseClick('primary', 354, 361, 1, 0)